In [269]:
#!pip install pymongo

In [270]:
import pandas as pd
from pymongo import MongoClient
from pymongo.errors import OperationFailure

## Lesson 1

In [271]:
url = 'mongodb://localhost:27017'
client = MongoClient(url)

try:
    db = client['mydb']
    collection = db['orders']
    
    cursor = collection.find()
    
    for s in cursor:
        print(f"{s['name']} : {s['cost']}" )
    cursor.close()

except OperationFailure as e:
    print(f"Error:\n {e}")
finally:
    client.close()
    
client.close()

Thomson Yeung : 888
Alice Wong : 999
Ada Pang : 5

## Lesson 2

In [272]:
def show_collect(mycol, myquery):
    list_cur = list(mycol.find(myquery))
    df = pd.DataFrame(list_cur)

    cols = list(df.columns)
    df = df[cols[1:]]
    return(df)

def show_collect_sort(mycol, mysort):
    list_cur = list(mycol.find().sort(mysort['field'], mysort['asc']))
    #list_cur = list(mycol.find().sort(mysort))
    df = pd.DataFrame(list_cur)

    cols = list(df.columns)
    df = df[cols[1:]]
    return(df)

In [273]:
tutorial1 = {
     "title": "Reading and Writing CSV Files in Python",
     "author": "Jon",
     "contributors": [
         "Aldren",
         "Geir Arne",
         "Joanna",
         "Jason"
     ],
     "url": "https://realpython.com/python-csv/"
}

tutorial2 = {
    "title": "How to Iterate Through a Dictionary in Python",
    "author": "Leodanis",
    "contributors": [
        "Aldren",
        "Jim",
        "Joanna"
    ],
    "url": "https://realpython.com/iterate-through-dictionary-python/"
}

tutorial3 = {
      "title": "Python 3's f-Strings: An Improved String Formatting Syntax",
      "author": "Joanna",
      "contributors": [
          "Adriana",
          "David",
          "Dan",
          "Jim",
          "Pavel"
      ],
      "url": "https://realpython.com/python-f-strings/"
}

tutorial4 = {
      "title": "Basket Ball Training",
      "author": "Coach Fui",
      "contributors": [
          "Thomson Yeung",
          "Adam Ma"
      ],
      "url": "https://basketball.com/coachfui/"
}

In [274]:
url = 'mongodb://localhost:27017'
client = MongoClient(url)

db = client['mydb']
tutorials = db['tutorials']

tutorials.delete_many({})
tutorials.insert_many([tutorial1, tutorial2, tutorial3])


#client.close()

In [275]:
tutorials.insert_one(tutorial4)

In [276]:
df_tutorials = show_collect(tutorials, {})
df_tutorials
# select * from tutorials

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
3,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [277]:
myquery = {'author': 'Joanna'}
df_tutorials = show_collect(tutorials, myquery)
df_tutorials
# select * from tutorials where author = 'Joanna'

,title,author,contributors,url
0,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/

In [278]:
myquery = {'author': {'$ne': 'Joanna'}}
df_tutorials = show_collect(tutorials, myquery)
df_tutorials
# select * from tutorials where author <> 'Joanna'

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [279]:
myquery = {'title': {'$regex': '^Python'}}
df_tutorials = show_collect(tutorials, myquery)
df_tutorials
# select * from tutorials where title like 'Python%'

,title,author,contributors,url
0,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/

In [280]:
mysort = {'field': 'title', 'asc': 1}
df_tutorials = show_collect_sort(tutorials, mysort)
df_tutorials
# select * from tutorials order by title asc

,title,author,contributors,url
0,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
3,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/

In [281]:
mysort = {'field': 'title', 'asc': -1}
#mysort = {'title':  -1}

df_tutorials = show_collect_sort(tutorials, mysort)
df_tutorials
# select * from tutorials order by title desc

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
2,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
3,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [282]:
myquery = {'author': 'Joanna'}
tutorials.delete_many(myquery)
df_tutorials = show_collect(tutorials, {})
df_tutorials
# delete from tutorials where author = 'Joanna'

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [283]:
tutorials.delete_many({})
tutorials.insert_many([tutorial1, tutorial2, tutorial3, tutorial4])
df_tutorials = show_collect(tutorials, {})
df_tutorials
# rollback

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
3,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [284]:
myquery = { "author": "Jon" }
newvalues = { "$set": { "author": "Thomson Yeung" } }

tutorials.update_one(myquery, newvalues)
df_tutorials = show_collect(tutorials, {})
df_tutorials
# update tutorials set author = 'Thomson Yeung' where author = 'Jon'

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Thomson Yeung,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
3,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [285]:
myquery = { "author": {"$ne": "Thomson Yeung" }}
newvalues = { "$set": { "author": "Alice Wong" } }

tutorials.update_many(myquery, newvalues)
df_tutorials = show_collect(tutorials, {})
df_tutorials
# update tutorials set author = 'Alice Wong' where author <> 'Thomson Yeung'

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Thomson Yeung,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Alice Wong,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Python 3's f-Strings: An Improved String Forma...,Alice Wong,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
3,Basket Ball Training,Alice Wong,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [286]:
tutorials.delete_many({})
tutorials.insert_many([tutorial1, tutorial2, tutorial3, tutorial4])
df_tutorials = show_collect(tutorials, {})
df_tutorials
# rollback

,title,author,contributors,url
0,Reading and Writing CSV Files in Python,Jon,"[Aldren, Geir Arne, Joanna, Jason]",https://realpython.com/python-csv/
1,How to Iterate Through a Dictionary in Python,Leodanis,"[Aldren, Jim, Joanna]",https://realpython.com/iterate-through-diction...
2,Python 3's f-Strings: An Improved String Forma...,Joanna,"[Adriana, David, Dan, Jim, Pavel]",https://realpython.com/python-f-strings/
3,Basket Ball Training,Coach Fui,"[Thomson Yeung, Adam Ma]",https://basketball.com/coachfui/

In [287]:
D_name={}
for index, row in df_tutorials.iterrows():
    D_name[index] = row['title']
    print(f"{index+1}. Contributors of title: {D_name[index]}")
    for i in row['contributors']:
        print(" - ", i)
    #print(index, row['Name'])
D_name

1. Contributors of title: Reading and Writing CSV Files in Python
 -  Aldren
 -  Geir Arne
 -  Joanna
 -  Jason
2. Contributors of title: How to Iterate Through a Dictionary in Python
 -  Aldren
 -  Jim
 -  Joanna
3. Contributors of title: Python 3's f-Strings: An Improved String Formatting Syntax
 -  Adriana
 -  David
 -  Dan
 -  Jim
 -  Pavel
4. Contributors of title: Basket Ball Training
 -  Thomson Yeung
 -  Adam Ma

{0: 'Reading and Writing CSV Files in Python',
 1: 'How to Iterate Through a Dictionary in Python',
 2: "Python 3's f-Strings: An Improved String Formatting Syntax",
 3: 'Basket Ball Training'}

In [288]:
client.close()